name: comp
channels:
    - psi4
    - conda-forge
dependencies:
    - python=3.9
    - psi4
    - sympy
    - scipy
    - numpy
    - matplotlib
    - nglview
    - jupyter
    - mdtraj
    - openmm
    - openbabel
